# Generated by `rails seeds:dump_bot`. Source bot: "templates".
# Edit the bot in-app and rerun the task; do not hand-edit this file.

require_relative 'helpers'

user = seed_user!

seed_bot = user.bots.find_or_initialize_by(name: "Seed Bot")
seed_bot.description = ""
seed_bot.save!

reset_bot_graph!(seed_bot)

node_map = { 113555 => seed_bot.root_node }

node_map[113560] = create_score!(
  bot: seed_bot,
  position_x: -4335.498779708767,
  position_y: 1822.0234375,
  action_type: "return",
  value: -1000
)

node_map[113561] = create_score!(
  bot: seed_bot,
  position_x: -2009.4531250000005,
  position_y: 3496.01171875,
  action_type: "add",
  value: 16
)

node_map[113563] = create_condition!(
  bot: seed_bot,
  position_x: -741.5397727272727,
  position_y: 962.583096590909,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "queen",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "less_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113565] = create_condition!(
  bot: seed_bot,
  position_x: -741.5085227272727,
  position_y: 1172.879971590909,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "queen",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113567] = create_condition!(
  bot: seed_bot,
  position_x: -2280.046875,
  position_y: 2415.306640625,
  data: {
    "version" => 2,
    "kind" => "census",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "count",
    "comparator" => "less_than",
    "subjectFilterMode" => "exclude",
    "target" => "exact_number",
    "targetTotal" => 4
  }
)

node_map[113568] = create_condition!(
  bot: seed_bot,
  position_x: -4624.992282326948,
  position_y: 1583.720703125,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "equal_to",
    "targetTotal" => 0,
    "subjectFilter" => "any"
  }
)

node_map[113569] = create_score!(
  bot: seed_bot,
  position_x: -4624.992282326948,
  position_y: 1806.517578125,
  action_type: "return",
  value: 1000
)

node_map[113570] = create_condition!(
  bot: seed_bot,
  position_x: 6254.15625,
  position_y: 2935.875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "allied",
    "targetFilter" => "king",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "less_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113571] = create_condition!(
  bot: seed_bot,
  position_x: 5318.875,
  position_y: 3133.484375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113572] = create_condition!(
  bot: seed_bot,
  position_x: 7385.96875,
  position_y: 3194.28125,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113573] = create_condition!(
  bot: seed_bot,
  position_x: 4898.90625,
  position_y: 3228.0625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "pawn",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include"
  }
)

node_map[113576] = create_condition!(
  bot: seed_bot,
  position_x: 6248.65625,
  position_y: 3156.90625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "major",
    "targetFilterMode" => "exclude"
  }
)

node_map[113577] = create_score!(
  bot: seed_bot,
  position_x: 5660.521052230999,
  position_y: 3144.7880746140045,
  action_type: "add",
  value: 5
)

node_map[113586] = create_condition!(
  bot: seed_bot,
  position_x: -2913.3750000000005,
  position_y: 3074.052734375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "pawn",
    "targetFilterMode" => "include"
  }
)

node_map[113587] = create_condition!(
  bot: seed_bot,
  position_x: -3756.1176325900624,
  position_y: 3177.9928305798194,
  data: {
    "kind" => "census",
    "target" => "prior_board_state",
    "subject" => "moved_piece",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "greater_than",
    "subjectFilter" => "any"
  }
)

node_map[113588] = create_condition!(
  bot: seed_bot,
  position_x: -2760.46875,
  position_y: 3086.6796875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "allied",
    "targetFilter" => "pawn",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113589] = create_condition!(
  bot: seed_bot,
  position_x: -2011.5156250000005,
  position_y: 3257.12109375,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "captured_piece",
    "version" => 2,
    "operator" => "count",
    "comparator" => "equal_to",
    "targetTotal" => 1,
    "subjectFilter" => "pawn",
    "subjectFilterMode" => "include"
  }
)

node_map[113590] = create_condition!(
  bot: seed_bot,
  position_x: -1849.7968750000005,
  position_y: 3244.90234375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113591] = create_condition!(
  bot: seed_bot,
  position_x: -3332.196374144759,
  position_y: 3128.6143462957725,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "rook",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "king",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113603] = create_organizer!(
  bot: seed_bot,
  position_x: -3236.328125,
  position_y: 3588.265625,
  title: "explainer",
  notes: "the above condition leverages the fact that a king cannot be attacked before and after a move, so the attacker count must be 0, which helps the odds that the move is in fact castling"
)

node_map[113604] = create_condition!(
  bot: seed_bot,
  position_x: -2280.046875,
  position_y: 2196.806640625,
  data: {
    "version" => 2,
    "kind" => "census",
    "subject" => "allied",
    "subjectFilter" => "pawn",
    "operator" => "count",
    "comparator" => "less_than",
    "subjectFilterMode" => "exclude",
    "target" => "exact_number",
    "targetTotal" => 4
  }
)

node_map[113610] = create_condition!(
  bot: seed_bot,
  position_x: 1992.330412231655,
  position_y: 3146.068934024262,
  data: {
    "kind" => "relational",
    "target" => "moved_piece",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "attack",
    "targetFilter" => "any",
    "subjectFilter" => "pawn",
    "targetComparator" => "less_than",
    "subjectComparator" => "equal_to",
    "subjectFilterMode" => "include",
    "targetComparisonMetric" => "individual_value",
    "targetComparisonSource" => "exact_number",
    "subjectComparisonMetric" => "count",
    "subjectComparisonSource" => "exact_number",
    "targetComparisonSourceTotal" => 9,
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113619] = create_condition!(
  bot: seed_bot,
  position_x: -3389.0625000000005,
  position_y: 3565.80859375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "allied",
    "targetFilter" => "rook",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113654] = create_condition!(
  bot: seed_bot,
  position_x: -2595.90625,
  position_y: 3082.3359375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "pawn",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113656] = create_condition!(
  bot: seed_bot,
  position_x: -2169.2187500000005,
  position_y: 3251.68359375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "subjectFilterMode" => "exclude",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113657] = create_score!(
  bot: seed_bot,
  position_x: -2180.1093750000005,
  position_y: 3482.46484375,
  action_type: "add",
  value: 15
)

node_map[113658] = create_score!(
  bot: seed_bot,
  position_x: -1864.7031250000005,
  position_y: 3453.66796875,
  action_type: "add",
  value: 19
)

node_map[113659] = create_condition!(
  bot: seed_bot,
  position_x: -4880.754743613422,
  position_y: 3223.9061694182483,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "exclude",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "less_than_or_equal_to",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113660] = create_condition!(
  bot: seed_bot,
  position_x: -3333.8750000000005,
  position_y: 3347.44921875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "king",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113661] = create_condition!(
  bot: seed_bot,
  position_x: -3873.0902180434427,
  position_y: 3361.523298153681,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "bishop",
    "operator" => "adjacent",
    "target" => "allied",
    "targetFilter" => "king",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "include",
    "targetComparisonMetric" => "count",
    "targetComparator" => "less_than",
    "targetComparisonSource" => "prior_board_state"
  }
)

node_map[113675] = create_organizer!(
  bot: seed_bot,
  position_x: -3082.811279708767,
  position_y: 837.53125,
  title: "Organizer",
  notes: ""
)

node_map[113676] = create_organizer!(
  bot: seed_bot,
  position_x: 213.890625,
  position_y: 2273.3125,
  title: "Organizer",
  notes: ""
)

node_map[113677] = create_organizer!(
  bot: seed_bot,
  position_x: 5770.828125,
  position_y: 2003.71875,
  title: "Organizer",
  notes: ""
)

node_map[113680] = create_organizer!(
  bot: seed_bot,
  position_x: -2302.046875,
  position_y: 2002.931640625,
  title: "Endgame",
  notes: ""
)

node_map[113681] = create_organizer!(
  bot: seed_bot,
  position_x: -4360.748779708767,
  position_y: 1168.9140625,
  title: "Avoid Stalemate",
  notes: ""
)

node_map[113683] = create_condition!(
  bot: seed_bot,
  position_x: -4340.764404708767,
  position_y: 1366.3046875,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "equal_to",
    "targetTotal" => 0,
    "subjectFilter" => "any"
  }
)

node_map[113684] = create_organizer!(
  bot: seed_bot,
  position_x: 7133.46875,
  position_y: 2786.515625,
  title: "Free capture",
  notes: ""
)

node_map[113685] = create_condition!(
  bot: seed_bot,
  position_x: 7155.40625,
  position_y: 2980.421875,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "captured_piece",
    "version" => 2,
    "operator" => "count",
    "comparator" => "equal_to",
    "targetTotal" => 1,
    "subjectFilter" => "any"
  }
)

node_map[113686] = create_condition!(
  bot: seed_bot,
  position_x: 7158.578125,
  position_y: 3202.90625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113687] = create_condition!(
  bot: seed_bot,
  position_x: -4340.764404708767,
  position_y: 1605.4296875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "king",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113688] = create_organizer!(
  bot: seed_bot,
  position_x: -2787.421875,
  position_y: 2872.6484375,
  title: "push safe pawns",
  notes: ""
)

node_map[113689] = create_organizer!(
  bot: seed_bot,
  position_x: 5300.015625,
  position_y: 2728.296875,
  title: "avoid hanging pieces",
  notes: ""
)

node_map[113690] = create_condition!(
  bot: seed_bot,
  position_x: 5318.34375,
  position_y: 2928.3125,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "captured_piece",
    "version" => 2,
    "operator" => "count",
    "comparator" => "equal_to",
    "targetTotal" => 0,
    "subjectFilter" => "any"
  }
)

node_map[113691] = create_organizer!(
  bot: seed_bot,
  position_x: 7375.140625,
  position_y: 2792.09375,
  title: "Safe promotion",
  notes: ""
)

node_map[113692] = create_condition!(
  bot: seed_bot,
  position_x: 7393.671875,
  position_y: 2984.25,
  data: {
    "kind" => "census",
    "target" => "prior_board_state",
    "subject" => "moved_piece",
    "version" => 2,
    "operator" => "value",
    "comparator" => "greater_than",
    "subjectFilter" => "any"
  }
)

node_map[113694] = create_organizer!(
  bot: seed_bot,
  position_x: -3781.420964688708,
  position_y: 1859.169417617857,
  title: "Opening Game Condition",
  notes: ""
)

node_map[113695] = create_organizer!(
  bot: seed_bot,
  position_x: -2009.7812500000002,
  position_y: 2821.05859375,
  title: "Attack pawns",
  notes: ""
)

node_map[113700] = create_organizer!(
  bot: seed_bot,
  position_x: 4881.84375,
  position_y: 2817.140625,
  title: "Kick material",
  notes: ""
)

node_map[113701] = create_condition!(
  bot: seed_bot,
  position_x: 4902.0,
  position_y: 3012.6875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "exclude"
  }
)

node_map[113702] = create_score!(
  bot: seed_bot,
  position_x: 7157.546875,
  position_y: 3476.265625,
  action_type: "add",
  value: 60
)

node_map[113709] = create_organizer!(
  bot: seed_bot,
  position_x: -813.0455731149591,
  position_y: 2657.65625,
  title: "Discoverd attack",
  notes: ""
)

node_map[113711] = create_organizer!(
  bot: seed_bot,
  position_x: -587.4205731149591,
  position_y: 2674.921875,
  title: "Open file rook",
  notes: ""
)

node_map[113714] = create_organizer!(
  bot: seed_bot,
  position_x: 666.4856768850404,
  position_y: 2769.1875,
  title: "Connect majors",
  notes: ""
)

node_map[113715] = create_organizer!(
  bot: seed_bot,
  position_x: 6235.703125,
  position_y: 2727.640625,
  title: "Escape check safely",
  notes: ""
)

node_map[113720] = create_organizer!(
  bot: seed_bot,
  position_x: -1163.7624616794856,
  position_y: 2668.782128659633,
  title: "Knight Fork",
  notes: ""
)

node_map[113724] = create_condition!(
  bot: seed_bot,
  position_x: -4624.992282326948,
  position_y: 1365.095703125,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "king",
    "targetFilterMode" => "include"
  }
)

node_map[113725] = create_organizer!(
  bot: seed_bot,
  position_x: -4633.054782326948,
  position_y: 1150.080078125,
  title: "Checkmate",
  notes: ""
)

node_map[113726] = create_organizer!(
  bot: seed_bot,
  position_x: 6937.698217343537,
  position_y: 2797.594737804577,
  title: "Avoid Pawn Attacks",
  notes: ""
)

node_map[113727] = create_organizer!(
  bot: seed_bot,
  position_x: 1533.2070894706833,
  position_y: 2771.830488498473,
  title: "Winning Capture",
  notes: ""
)

node_map[113730] = create_organizer!(
  bot: seed_bot,
  position_x: 5648.892859746634,
  position_y: 2730.0870482486785,
  title: "Improve Pawn Mobility",
  notes: ""
)

node_map[113731] = create_condition!(
  bot: seed_bot,
  position_x: -3760.9458139193925,
  position_y: 2125.8733954881745,
  data: {
    "version" => 2,
    "kind" => "census",
    "subject" => "allied",
    "subjectFilter" => "king",
    "operator" => "value",
    "comparator" => "greater_than",
    "subjectFilterMode" => "exclude",
    "target" => "exact_number",
    "targetTotal" => 34
  }
)

node_map[113732] = create_organizer!(
  bot: seed_bot,
  position_x: -185.5063524205002,
  position_y: 2693.1601927111583,
  title: "Bishop Fork",
  notes: ""
)

node_map[113733] = create_organizer!(
  bot: seed_bot,
  position_x: 1977.3064900635445,
  position_y: 2765.7349187727013,
  title: "King Pin",
  notes: ""
)

node_map[113734] = create_organizer!(
  bot: seed_bot,
  position_x: 1207.6820161129208,
  position_y: 2772.9703634992834,
  title: "Queen skewer",
  notes: ""
)

node_map[113735] = create_organizer!(
  bot: seed_bot,
  position_x: 2427.6194950397376,
  position_y: 2778.077466128586,
  title: "Rook Pin",
  notes: ""
)

node_map[113737] = create_score!(
  bot: seed_bot,
  position_x: 6961.5650880274725,
  position_y: 3213.946145419119,
  action_type: "subtract",
  value: 8
)

node_map[113738] = create_condition!(
  bot: seed_bot,
  position_x: 2448.3973684264756,
  position_y: 2989.370212272568,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "shield",
    "target" => "enemy",
    "targetFilter" => "rook",
    "subjectFilterMode" => "exclude",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113739] = create_condition!(
  bot: seed_bot,
  position_x: 2459.231904850285,
  position_y: 3218.420897033535,
  data: {
    "kind" => "relational",
    "target" => "moved_piece",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "attack",
    "targetFilter" => "any",
    "subjectFilter" => "pawn",
    "targetComparator" => "less_than",
    "subjectComparator" => "equal_to",
    "subjectFilterMode" => "include",
    "targetComparisonMetric" => "individual_value",
    "targetComparisonSource" => "exact_number",
    "subjectComparisonMetric" => "count",
    "subjectComparisonSource" => "exact_number",
    "targetComparisonSourceTotal" => 5,
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113741] = create_condition!(
  bot: seed_bot,
  position_x: 3351.4444507512094,
  position_y: 2863.1232313239634,
  data: {
    "kind" => "census",
    "target" => "prior_board_state",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "less_than",
    "subjectFilter" => "king",
    "subjectFilterMode" => "include"
  }
)

node_map[113742] = create_organizer!(
  bot: seed_bot,
  position_x: 3331.8719633958895,
  position_y: 2682.876395569782,
  title: "Tighten The Net",
  notes: ""
)

node_map[113744] = create_condition!(
  bot: seed_bot,
  position_x: 3347.626833171455,
  position_y: 3059.1654981665515,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113746] = create_organizer!(
  bot: seed_bot,
  position_x: -891.171875,
  position_y: 747.04296875,
  title: "Queen safety",
  notes: ""
)

node_map[113747] = create_condition!(
  bot: seed_bot,
  position_x: -996.359375,
  position_y: 960.88671875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "queen",
    "targetFilterMode" => "include"
  }
)

node_map[113748] = create_condition!(
  bot: seed_bot,
  position_x: -1853.7343750000005,
  position_y: 3020.24609375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "targetFilterMode" => "include"
  }
)

node_map[113749] = create_condition!(
  bot: seed_bot,
  position_x: -1151.209339263717,
  position_y: 2881.7625952486137,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "knight",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "exclude",
    "targetComparisonMetric" => "count",
    "targetComparator" => "greater_than",
    "targetComparisonSource" => "exact_number",
    "targetComparisonSourceTotal" => 1
  }
)

node_map[113750] = create_condition!(
  bot: seed_bot,
  position_x: -1272.787464263717,
  position_y: 3025.7782202486137,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113751] = create_condition!(
  bot: seed_bot,
  position_x: -1034.240589263717,
  position_y: 3022.1844702486137,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113752] = create_condition!(
  bot: seed_bot,
  position_x: -1271.4164474609734,
  position_y: 3208.4046918720137,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113753] = create_condition!(
  bot: seed_bot,
  position_x: -785.9361981149591,
  position_y: 2881.265625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "targetFilterMode" => "exclude",
    "targetComparisonMetric" => "count",
    "targetComparator" => "equal_to",
    "targetComparisonSource" => "exact_number",
    "targetComparisonSourceTotal" => 0
  }
)

node_map[113754] = create_organizer!(
  bot: seed_bot,
  position_x: 327.0173684149913,
  position_y: 2774.157209771902,
  title: "Rook skewer",
  notes: ""
)

node_map[113756] = create_condition!(
  bot: seed_bot,
  position_x: 682.7044268850404,
  position_y: 2948.890625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "major",
    "operator" => "defend",
    "target" => "allied",
    "targetFilter" => "major",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113757] = create_condition!(
  bot: seed_bot,
  position_x: -165.29698000473172,
  position_y: 2908.281284300139,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "bishop",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "exclude",
    "targetComparisonMetric" => "count",
    "targetComparator" => "greater_than",
    "targetComparisonSource" => "exact_number",
    "targetComparisonSourceTotal" => 1
  }
)

node_map[113765] = create_condition!(
  bot: seed_bot,
  position_x: 3877.48613179531,
  position_y: 2924.5055475514464,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "captured_piece",
    "version" => 2,
    "operator" => "count",
    "comparator" => "equal_to",
    "targetTotal" => 1,
    "subjectFilter" => "any"
  }
)

node_map[113766] = create_condition!(
  bot: seed_bot,
  position_x: 3792.576649422401,
  position_y: 3390.915819821521,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113767] = create_condition!(
  bot: seed_bot,
  position_x: 4001.28902240323,
  position_y: 3270.9168463850383,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113771] = create_condition!(
  bot: seed_bot,
  position_x: 3880.026377114962,
  position_y: 3130.4197396842847,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "shield",
    "target" => "enemy",
    "targetFilter" => "king",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "less_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113772] = create_condition!(
  bot: seed_bot,
  position_x: 4001.7812297194623,
  position_y: 3480.336139731362,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113773] = create_organizer!(
  bot: seed_bot,
  position_x: 3859.0,
  position_y: 2750.40625,
  title: "Strip King Shelter",
  notes: ""
)

node_map[113777] = create_score!(
  bot: seed_bot,
  position_x: 3901.0745427870324,
  position_y: 3633.6654532437497,
  action_type: "add",
  value: 18
)

node_map[113782] = create_organizer!(
  bot: seed_bot,
  position_x: -4280.63677348514,
  position_y: 2708.4195396468667,
  title: "Safe Bishop Development",
  notes: ""
)

node_map[113783] = create_condition!(
  bot: seed_bot,
  position_x: -4261.554774452528,
  position_y: 2906.2604691855768,
  data: {
    "kind" => "census",
    "target" => "prior_board_state",
    "subject" => "moved_piece",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "greater_than",
    "subjectFilter" => "bishop",
    "subjectFilterMode" => "include"
  }
)

node_map[113785] = create_condition!(
  bot: seed_bot,
  position_x: -4763.875847814891,
  position_y: 3040.932221918951,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113786] = create_condition!(
  bot: seed_bot,
  position_x: -4267.562635702481,
  position_y: 3107.6559219041715,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113787] = create_condition!(
  bot: seed_bot,
  position_x: -4670.995582920152,
  position_y: 3333.822283149475,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113788] = create_condition!(
  bot: seed_bot,
  position_x: -4384.441531501011,
  position_y: 3290.6298694034685,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "exclude",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "less_than_or_equal_to",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113789] = create_condition!(
  bot: seed_bot,
  position_x: -4174.682370807741,
  position_y: 3400.5459831346952,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113790] = create_condition!(
  bot: seed_bot,
  position_x: -4882.633610350878,
  position_y: 3429.3396379843625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113791] = create_condition!(
  bot: seed_bot,
  position_x: -4386.3203982384675,
  position_y: 3496.063337969583,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectFilterMode" => "include",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113793] = create_score!(
  bot: seed_bot,
  position_x: -2757.78125,
  position_y: 3332.365234375,
  action_type: "return",
  value: 7
)

node_map[113794] = create_score!(
  bot: seed_bot,
  position_x: -3393.4375000000005,
  position_y: 3794.51171875,
  action_type: "add",
  value: 12
)

node_map[113820] = create_organizer!(
  bot: seed_bot,
  position_x: 4376.151829733777,
  position_y: 2807.452689985601,
  title: "Direct King Pressure",
  notes: ""
)

node_map[113821] = create_score!(
  bot: seed_bot,
  position_x: 4401.193021609129,
  position_y: 3639.411500538742,
  action_type: "add",
  value: 15
)

node_map[113822] = create_condition!(
  bot: seed_bot,
  position_x: 4303.266207715957,
  position_y: 2990.500921108639,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "king",
    "targetFilterMode" => "include"
  }
)

node_map[113823] = create_condition!(
  bot: seed_bot,
  position_x: 4307.260072839197,
  position_y: 3337.3689358026386,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113824] = create_condition!(
  bot: seed_bot,
  position_x: 4508.921875,
  position_y: 3247.96875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113825] = create_condition!(
  bot: seed_bot,
  position_x: 4509.677470459907,
  position_y: 3466.1342708136744,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113828] = create_condition!(
  bot: seed_bot,
  position_x: 1225.0016775531976,
  position_y: 2969.8962641264607,
  data: {
    "kind" => "relational",
    "target" => "enemy",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "shield",
    "targetFilter" => "pawn",
    "subjectFilter" => "queen",
    "targetFilterMode" => "exclude",
    "subjectComparator" => "greater_than",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "individual_value",
    "subjectComparisonSource" => "moved_piece"
  }
)

node_map[113829] = create_condition!(
  bot: seed_bot,
  position_x: 1227.0286666615566,
  position_y: 3165.4917359448646,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113830] = create_condition!(
  bot: seed_bot,
  position_x: 1139.7866454958819,
  position_y: 3370.499839583056,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113831] = create_condition!(
  bot: seed_bot,
  position_x: 1343.5494244145664,
  position_y: 3376.6635775143245,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113841] = create_condition!(
  bot: seed_bot,
  position_x: 6966.7682130274725,
  position_y: 3007.1478409134256,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "pawn",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "exclude"
  }
)

node_map[113842] = create_condition!(
  bot: seed_bot,
  position_x: 1556.419515022532,
  position_y: 2997.1642839047167,
  data: {
    "kind" => "census",
    "target" => "moved_piece",
    "subject" => "captured_piece",
    "version" => 2,
    "operator" => "value",
    "comparator" => "greater_than",
    "targetFilter" => "any",
    "subjectFilter" => "any"
  }
)

node_map[113844] = create_condition!(
  bot: seed_bot,
  position_x: 1995.3936548979318,
  position_y: 2952.713771969621,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "shield",
    "target" => "enemy",
    "targetFilter" => "king",
    "subjectFilterMode" => "exclude",
    "targetFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113845] = create_condition!(
  bot: seed_bot,
  position_x: 350.4236184149913,
  position_y: 2960.782209771902,
  data: {
    "kind" => "relational",
    "target" => "enemy",
    "subject" => "enemy",
    "version" => 2,
    "operator" => "shield",
    "targetFilter" => "pawn",
    "subjectFilter" => "rook",
    "targetFilterMode" => "exclude",
    "subjectComparator" => "greater_than",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "individual_value",
    "subjectComparisonSource" => "moved_piece"
  }
)

node_map[113848] = create_condition!(
  bot: seed_bot,
  position_x: 5670.503695507774,
  position_y: 2929.025739166401,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "pawn",
    "operator" => "defend",
    "target" => "allied",
    "targetFilter" => "pawn",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "include",
    "targetComparisonMetric" => "count",
    "targetComparator" => "greater_than",
    "targetComparisonSource" => "prior_board_state"
  }
)

node_map[113850] = create_condition!(
  bot: seed_bot,
  position_x: -3760.0783159476928,
  position_y: 2343.034009849559,
  data: {
    "version" => 2,
    "kind" => "census",
    "subject" => "enemy",
    "subjectFilter" => "king",
    "operator" => "value",
    "comparator" => "greater_than",
    "subjectFilterMode" => "exclude",
    "target" => "exact_number",
    "targetTotal" => 34
  }
)

node_map[113851] = create_condition!(
  bot: seed_bot,
  position_x: -786.5299481149591,
  position_y: 3107.140625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "enemy",
    "targetFilter" => "pawn",
    "targetFilterMode" => "exclude",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "prior_board_state"
  }
)

node_map[113852] = create_condition!(
  bot: seed_bot,
  position_x: -572.6549481149591,
  position_y: 3067.015625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "major",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "exclude",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113853] = create_score!(
  bot: seed_bot,
  position_x: 679.8919268850404,
  position_y: 3174.109375,
  action_type: "add",
  value: 8
)

node_map[113855] = create_score!(
  bot: seed_bot,
  position_x: 1552.419515022532,
  position_y: 3223.74647198286,
  action_type: "add",
  value: 200
)

node_map[113856] = create_condition!(
  bot: seed_bot,
  position_x: -303.4532300047317,
  position_y: 3052.921909300139,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113857] = create_condition!(
  bot: seed_bot,
  position_x: 347.14109021355125,
  position_y: 3197.0337271166313,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113861] = create_condition!(
  bot: seed_bot,
  position_x: 6107.875,
  position_y: 3133.78125,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "pawn",
    "targetFilterMode" => "include"
  }
)

node_map[113865] = create_organizer!(
  bot: seed_bot,
  position_x: -4760.984985725112,
  position_y: 2638.657170739176,
  title: "Safe Knight Development",
  notes: ""
)

node_map[113866] = create_organizer!(
  bot: seed_bot,
  position_x: -3777.5860680594838,
  position_y: 2791.7209359759277,
  title: "castling",
  notes: ""
)

node_map[113867] = create_condition!(
  bot: seed_bot,
  position_x: -782.640625,
  position_y: 3332.9375,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113868] = create_condition!(
  bot: seed_bot,
  position_x: -573.1393231149591,
  position_y: 3286.171875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "major",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include"
  }
)

node_map[113869] = create_score!(
  bot: seed_bot,
  position_x: -1043.8712217016237,
  position_y: 3351.593014450028,
  action_type: "add",
  value: 30
)

node_map[113870] = create_condition!(
  bot: seed_bot,
  position_x: -301.394713201988,
  position_y: 3293.767130923539,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "pawn",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectFilterMode" => "include",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113871] = create_condition!(
  bot: seed_bot,
  position_x: -29.609480004731722,
  position_y: 3057.078159300139,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113872] = create_score!(
  bot: seed_bot,
  position_x: -29.083862442638292,
  position_y: 3440.642953501553,
  action_type: "add",
  value: 20
)

node_map[113873] = create_condition!(
  bot: seed_bot,
  position_x: 1895.531669852923,
  position_y: 3344.650444584155,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113874] = create_condition!(
  bot: seed_bot,
  position_x: 2072.594185745452,
  position_y: 3348.363904111087,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113875] = create_condition!(
  bot: seed_bot,
  position_x: 2539.495678364082,
  position_y: 3420.7158671203597,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113876] = create_condition!(
  bot: seed_bot,
  position_x: 2362.4331624715533,
  position_y: 3417.002407593428,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113877] = create_condition!(
  bot: seed_bot,
  position_x: 463.66184796656125,
  position_y: 3408.2055686860913,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113878] = create_condition!(
  bot: seed_bot,
  position_x: 259.8990690478763,
  position_y: 3402.041830754823,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113881] = create_condition!(
  bot: seed_bot,
  position_x: 5322.796875,
  position_y: 3329.765625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "greater_than",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113884] = create_score!(
  bot: seed_bot,
  position_x: 6102.796875,
  position_y: 3363.53125,
  action_type: "add",
  value: 10
)

node_map[113887] = create_condition!(
  bot: seed_bot,
  position_x: 3267.247099773885,
  position_y: 3261.3843699876984,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "allied",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "moved_piece",
    "targetFilter" => "any"
  }
)

node_map[113888] = create_condition!(
  bot: seed_bot,
  position_x: 3439.596996407559,
  position_y: 3253.487177710754,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113892] = create_condition!(
  bot: seed_bot,
  position_x: -2170.8281250000005,
  position_y: 3017.48046875,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113893] = create_condition!(
  bot: seed_bot,
  position_x: -4757.867986564938,
  position_y: 2839.5367692003565,
  data: {
    "kind" => "census",
    "target" => "prior_board_state",
    "subject" => "moved_piece",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "greater_than",
    "subjectFilter" => "knight",
    "subjectFilterMode" => "include"
  }
)

node_map[113894] = create_condition!(
  bot: seed_bot,
  position_x: -3334.4845917069442,
  position_y: 2947.8234102331658,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "king",
    "operator" => "adjacent",
    "target" => "allied",
    "targetFilter" => "rook",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "include",
    "targetComparisonMetric" => "count",
    "targetComparator" => "equal_to",
    "targetComparisonSource" => "exact_number",
    "targetComparisonSourceTotal" => 1
  }
)

node_map[113895] = create_condition!(
  bot: seed_bot,
  position_x: -3758.004270491754,
  position_y: 2992.0332209939565,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "enemy",
    "subjectFilter" => "any",
    "operator" => "attack",
    "target" => "moved_piece",
    "targetFilter" => "any",
    "subjectComparisonMetric" => "count",
    "subjectComparator" => "equal_to",
    "subjectComparisonSource" => "exact_number",
    "subjectComparisonSourceTotal" => 0
  }
)

node_map[113897] = create_score!(
  bot: seed_bot,
  position_x: -785.2330731149591,
  position_y: 3548.5,
  action_type: "add",
  value: 20
)

node_map[113898] = create_score!(
  bot: seed_bot,
  position_x: 1992.8298452964027,
  position_y: 3561.4110521457,
  action_type: "add",
  value: 15
)

node_map[113899] = create_score!(
  bot: seed_bot,
  position_x: 1247.0511690184985,
  position_y: 3597.4337205237234,
  action_type: "add",
  value: 15
)

node_map[113900] = create_score!(
  bot: seed_bot,
  position_x: 2459.731337915033,
  position_y: 3633.763015154973,
  action_type: "add",
  value: 15
)

node_map[113901] = create_score!(
  bot: seed_bot,
  position_x: 367.16359257049317,
  position_y: 3628.97571169549,
  action_type: "return",
  value: 15
)

node_map[113903] = create_score!(
  bot: seed_bot,
  position_x: 5318.375,
  position_y: 3536.234375,
  action_type: "subtract",
  value: 20
)

node_map[113904] = create_score!(
  bot: seed_bot,
  position_x: 6325.703125,
  position_y: 3387.671875,
  action_type: "add",
  value: 5
)

node_map[113906] = create_score!(
  bot: seed_bot,
  position_x: 3359.426221574225,
  position_y: 3439.785624848163,
  action_type: "add",
  value: 17
)

node_map[113909] = create_score!(
  bot: seed_bot,
  position_x: -580.8580731149591,
  position_y: 3710.953125,
  action_type: "add",
  value: 7
)

node_map[113911] = create_condition!(
  bot: seed_bot,
  position_x: -3667.5050925411992,
  position_y: 3376.038736393131,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "knight",
    "operator" => "adjacent",
    "target" => "allied",
    "targetFilter" => "rook",
    "subjectFilterMode" => "include",
    "targetFilterMode" => "include",
    "targetComparisonMetric" => "count",
    "targetComparator" => "less_than",
    "targetComparisonSource" => "prior_board_state"
  }
)

node_map[113913] = create_score!(
  bot: seed_bot,
  position_x: -4771.3576043101475,
  position_y: 3622.455378339091,
  action_type: "add",
  value: 10
)

node_map[113914] = create_score!(
  bot: seed_bot,
  position_x: -3769.1022019620364,
  position_y: 3571.9791478546804,
  action_type: "add",
  value: 10
)

node_map[113915] = create_score!(
  bot: seed_bot,
  position_x: -4275.044392197737,
  position_y: 3689.1790783243114,
  action_type: "add",
  value: 10
)

node_map[113922] = create_condition!(
  bot: seed_bot,
  position_x: -575.25,
  position_y: 3504.65625,
  data: {
    "version" => 2,
    "kind" => "relational",
    "subject" => "moved_piece",
    "subjectFilter" => "any",
    "operator" => "defend",
    "target" => "allied",
    "targetFilter" => "pawn",
    "targetFilterMode" => "include",
    "targetComparisonMetric" => "count",
    "targetComparator" => "less_than",
    "targetComparisonSource" => "prior_board_state"
  }
)

node_map[113923] = create_condition!(
  bot: seed_bot,
  position_x: -572.4830731149591,
  position_y: 2857.0625,
  data: {
    "kind" => "census",
    "target" => "prior_board_state",
    "subject" => "moved_piece",
    "version" => 2,
    "operator" => "mobility",
    "comparator" => "greater_than",
    "subjectFilter" => "rook",
    "subjectFilterMode" => "include"
  }
)

node_map[113939] = create_score!(
  bot: seed_bot,
  position_x: 7384.0,
  position_y: 3415.265625,
  action_type: "add",
  value: 30
)

node_map[113940] = create_score!(
  bot: seed_bot,
  position_x: -1001.546875,
  position_y: 1216.07421875,
  action_type: "subtract",
  value: 20
)

node_map[113942] = create_score!(
  bot: seed_bot,
  position_x: 4893.21875,
  position_y: 3431.328125,
  action_type: "add",
  value: 15
)

node_map[113946] = create_score!(
  bot: seed_bot,
  position_x: -744.3678977272727,
  position_y: 1371.239346590909,
  action_type: "add",
  value: 150
)

node_map[113962] = create_condition!(
  bot: seed_bot,
  position_x: 6414.46875,
  position_y: 3153.890625,
  data: {
    "kind" => "census",
    "target" => "exact_number",
    "subject" => "moved_piece",
    "version" => 2,
    "operator" => "count",
    "comparator" => "greater_than",
    "targetTotal" => 0,
    "subjectFilter" => "king",
    "subjectFilterMode" => "include"
  }
)


connect!(node_map[113555], node_map[113675])
connect!(node_map[113555], node_map[113676])
connect!(node_map[113555], node_map[113677])
connect!(node_map[113555], node_map[113746])
connect!(node_map[113563], node_map[113565])
connect!(node_map[113565], node_map[113946])
connect!(node_map[113567], node_map[113688])
connect!(node_map[113567], node_map[113695])
connect!(node_map[113568], node_map[113569])
connect!(node_map[113570], node_map[113576])
connect!(node_map[113570], node_map[113861])
connect!(node_map[113570], node_map[113962])
connect!(node_map[113571], node_map[113881])
connect!(node_map[113572], node_map[113939])
connect!(node_map[113573], node_map[113942])
connect!(node_map[113576], node_map[113904])
connect!(node_map[113586], node_map[113793])
connect!(node_map[113587], node_map[113661])
connect!(node_map[113587], node_map[113911])
connect!(node_map[113588], node_map[113793])
connect!(node_map[113589], node_map[113561])
connect!(node_map[113590], node_map[113658])
connect!(node_map[113591], node_map[113660])
connect!(node_map[113604], node_map[113567])
connect!(node_map[113610], node_map[113873])
connect!(node_map[113610], node_map[113874])
connect!(node_map[113619], node_map[113794])
connect!(node_map[113654], node_map[113793])
connect!(node_map[113656], node_map[113657])
connect!(node_map[113659], node_map[113790])
connect!(node_map[113660], node_map[113603])
connect!(node_map[113660], node_map[113619])
connect!(node_map[113661], node_map[113914])
connect!(node_map[113675], node_map[113680])
connect!(node_map[113675], node_map[113681])
connect!(node_map[113675], node_map[113694])
connect!(node_map[113675], node_map[113725])
connect!(node_map[113676], node_map[113709])
connect!(node_map[113676], node_map[113711])
connect!(node_map[113676], node_map[113714])
connect!(node_map[113676], node_map[113720])
connect!(node_map[113676], node_map[113727])
connect!(node_map[113676], node_map[113732])
connect!(node_map[113676], node_map[113733])
connect!(node_map[113676], node_map[113734])
connect!(node_map[113676], node_map[113735])
connect!(node_map[113676], node_map[113754])
connect!(node_map[113677], node_map[113684])
connect!(node_map[113677], node_map[113689])
connect!(node_map[113677], node_map[113691])
connect!(node_map[113677], node_map[113700])
connect!(node_map[113677], node_map[113715])
connect!(node_map[113677], node_map[113726])
connect!(node_map[113677], node_map[113730])
connect!(node_map[113677], node_map[113742])
connect!(node_map[113677], node_map[113773])
connect!(node_map[113677], node_map[113820])
connect!(node_map[113680], node_map[113604])
connect!(node_map[113681], node_map[113683])
connect!(node_map[113683], node_map[113687])
connect!(node_map[113684], node_map[113685])
connect!(node_map[113685], node_map[113686])
connect!(node_map[113686], node_map[113702])
connect!(node_map[113687], node_map[113560])
connect!(node_map[113688], node_map[113586])
connect!(node_map[113688], node_map[113588])
connect!(node_map[113688], node_map[113654])
connect!(node_map[113689], node_map[113690])
connect!(node_map[113690], node_map[113571])
connect!(node_map[113691], node_map[113692])
connect!(node_map[113692], node_map[113572])
connect!(node_map[113694], node_map[113731])
connect!(node_map[113695], node_map[113748])
connect!(node_map[113695], node_map[113892])
connect!(node_map[113700], node_map[113701])
connect!(node_map[113701], node_map[113573])
connect!(node_map[113709], node_map[113753])
connect!(node_map[113711], node_map[113923])
connect!(node_map[113714], node_map[113756])
connect!(node_map[113715], node_map[113570])
connect!(node_map[113720], node_map[113749])
connect!(node_map[113724], node_map[113568])
connect!(node_map[113725], node_map[113724])
connect!(node_map[113726], node_map[113841])
connect!(node_map[113727], node_map[113842])
connect!(node_map[113730], node_map[113848])
connect!(node_map[113731], node_map[113850])
connect!(node_map[113732], node_map[113757])
connect!(node_map[113733], node_map[113844])
connect!(node_map[113734], node_map[113828])
connect!(node_map[113735], node_map[113738])
connect!(node_map[113738], node_map[113739])
connect!(node_map[113739], node_map[113875])
connect!(node_map[113739], node_map[113876])
connect!(node_map[113741], node_map[113744])
connect!(node_map[113742], node_map[113741])
connect!(node_map[113744], node_map[113887])
connect!(node_map[113744], node_map[113888])
connect!(node_map[113746], node_map[113563])
connect!(node_map[113746], node_map[113747])
connect!(node_map[113747], node_map[113940])
connect!(node_map[113748], node_map[113590])
connect!(node_map[113749], node_map[113750])
connect!(node_map[113749], node_map[113751])
connect!(node_map[113750], node_map[113752])
connect!(node_map[113751], node_map[113869])
connect!(node_map[113752], node_map[113869])
connect!(node_map[113753], node_map[113851])
connect!(node_map[113754], node_map[113845])
connect!(node_map[113756], node_map[113853])
connect!(node_map[113757], node_map[113856])
connect!(node_map[113757], node_map[113871])
connect!(node_map[113765], node_map[113771])
connect!(node_map[113766], node_map[113777])
connect!(node_map[113767], node_map[113772])
connect!(node_map[113771], node_map[113766])
connect!(node_map[113771], node_map[113767])
connect!(node_map[113772], node_map[113777])
connect!(node_map[113773], node_map[113765])
connect!(node_map[113782], node_map[113783])
connect!(node_map[113783], node_map[113786])
connect!(node_map[113785], node_map[113659])
connect!(node_map[113785], node_map[113787])
connect!(node_map[113786], node_map[113788])
connect!(node_map[113786], node_map[113789])
connect!(node_map[113787], node_map[113913])
connect!(node_map[113788], node_map[113791])
connect!(node_map[113789], node_map[113915])
connect!(node_map[113790], node_map[113913])
connect!(node_map[113791], node_map[113915])
connect!(node_map[113820], node_map[113822])
connect!(node_map[113822], node_map[113823])
connect!(node_map[113822], node_map[113824])
connect!(node_map[113823], node_map[113821])
connect!(node_map[113824], node_map[113825])
connect!(node_map[113825], node_map[113821])
connect!(node_map[113828], node_map[113829])
connect!(node_map[113829], node_map[113830])
connect!(node_map[113829], node_map[113831])
connect!(node_map[113830], node_map[113899])
connect!(node_map[113831], node_map[113899])
connect!(node_map[113841], node_map[113737])
connect!(node_map[113842], node_map[113855])
connect!(node_map[113844], node_map[113610])
connect!(node_map[113845], node_map[113857])
connect!(node_map[113848], node_map[113577])
connect!(node_map[113850], node_map[113782])
connect!(node_map[113850], node_map[113865])
connect!(node_map[113850], node_map[113866])
connect!(node_map[113851], node_map[113867])
connect!(node_map[113852], node_map[113868])
connect!(node_map[113856], node_map[113870])
connect!(node_map[113857], node_map[113877])
connect!(node_map[113857], node_map[113878])
connect!(node_map[113861], node_map[113884])
connect!(node_map[113865], node_map[113893])
connect!(node_map[113866], node_map[113894])
connect!(node_map[113866], node_map[113895])
connect!(node_map[113867], node_map[113897])
connect!(node_map[113868], node_map[113922])
connect!(node_map[113870], node_map[113872])
connect!(node_map[113871], node_map[113872])
connect!(node_map[113873], node_map[113898])
connect!(node_map[113874], node_map[113898])
connect!(node_map[113875], node_map[113900])
connect!(node_map[113876], node_map[113900])
connect!(node_map[113877], node_map[113901])
connect!(node_map[113878], node_map[113901])
connect!(node_map[113881], node_map[113903])
connect!(node_map[113887], node_map[113906])
connect!(node_map[113888], node_map[113906])
connect!(node_map[113892], node_map[113589])
connect!(node_map[113892], node_map[113656])
connect!(node_map[113893], node_map[113785])
connect!(node_map[113894], node_map[113591])
connect!(node_map[113895], node_map[113587])
connect!(node_map[113911], node_map[113914])
connect!(node_map[113922], node_map[113909])
connect!(node_map[113923], node_map[113852])
connect!(node_map[113962], node_map[113904])
