namespace :seeds do
  desc "Regenerate a db/seeds/*.rb dump from a bot in the DB. Usage: rails 'seeds:dump_bot[seed_bot]' (omit arg to dump all configured)."
  task :dump_bot, [:key] => :environment do |_t, args|
    BotSeedDumper.run(args[:key])
  end
end

class BotSeedDumper
  SEEDS_DIR = Rails.root.join('db/seeds')

  # key => source bot to read, target bot the generated seed builds, output filename under db/seeds.
  # Add an entry to dump another bot to its own seed file.
  DUMPS = {
    'seed_bot' => { source: 'templates', target: 'Seed Bot', filename: 'seed_bot.rb' }
  }.freeze

  def self.run(key = nil)
    keys = key.present? ? [key] : DUMPS.keys
    keys.each { |k| new(k).call }
  end

  def initialize(key)
    @config = DUMPS.fetch(key) do
      raise "Unknown dump #{key.inspect}. Known: #{DUMPS.keys.join(', ')}"
    end
  end

  def call
    bot = Bot.find_by!(name: @config[:source])
    File.write(SEEDS_DIR.join(@config[:filename]), render(bot))
    puts "Wrote #{@config[:filename]} from bot #{@config[:source].inspect} " \
         "(#{bot.nodes.count} nodes, #{bot.connections.count} connections)."
  end

  private

  def render(bot)
    root = bot.root_node
    body_nodes = bot.nodes.where.not(node_type: 'root').order(:id)
    connections = bot.connections.order(:source_node_id, :target_node_id)

    out = +''
    out << "# Generated by `rails seeds:dump_bot`. Source bot: #{@config[:source].inspect}.\n"
    out << "# Edit the bot in-app and rerun the task; do not hand-edit this file.\n\n"
    out << "require_relative 'helpers'\n\n"
    out << "user = seed_user!\n\n"
    out << "seed_bot = user.bots.find_or_initialize_by(name: #{@config[:target].inspect})\n"
    out << "seed_bot.description = #{bot.description.to_s.inspect}\n"
    out << "seed_bot.save!\n\n"
    out << "reset_bot_graph!(seed_bot)\n\n"
    out << "node_map = { #{root.id} => seed_bot.root_node }\n\n"

    body_nodes.each { |node| out << render_node(node) << "\n" }
    out << "\n"
    connections.each do |c|
      out << "connect!(node_map[#{c.source_node_id}], node_map[#{c.target_node_id}])\n"
    end
    out
  end

  def render_node(node)
    case node.node_type
    when 'condition'
      <<~RUBY
        node_map[#{node.id}] = create_condition!(
          bot: seed_bot,
          position_x: #{node.position_x},
          position_y: #{node.position_y},
          data: #{render_data(node.data)}
        )
      RUBY
    when 'score'
      <<~RUBY
        node_map[#{node.id}] = create_score!(
          bot: seed_bot,
          position_x: #{node.position_x},
          position_y: #{node.position_y},
          action_type: #{node.data['actionType'].inspect},
          value: #{node.data['value'].inspect}
        )
      RUBY
    when 'organizer'
      <<~RUBY
        node_map[#{node.id}] = create_organizer!(
          bot: seed_bot,
          position_x: #{node.position_x},
          position_y: #{node.position_y},
          title: #{node.data['title'].to_s.inspect},
          notes: #{node.data['notes'].to_s.inspect}
        )
      RUBY
    else
      raise "Unexpected node type #{node.node_type.inspect} on node ##{node.id}"
    end
  end

  def render_data(data)
    pairs = data.map { |key, value| "    #{key.inspect} => #{value.inspect}" }
    "{\n#{pairs.join(",\n")}\n  }"
  end
end
