export const TEMPLATE_CATEGORIES = Object.freeze({
  OPENING: 'opening',
  CAPTURES: 'captures',
  SAFETY: 'safety',
  ACTIVITY: 'activity',
  TACTICS: 'tactics',
  ENDGAME: 'endgame'
})

export const TEMPLATE_CATEGORY_ORDER = Object.freeze([
  TEMPLATE_CATEGORIES.OPENING,
  TEMPLATE_CATEGORIES.CAPTURES,
  TEMPLATE_CATEGORIES.SAFETY,
  TEMPLATE_CATEGORIES.ACTIVITY,
  TEMPLATE_CATEGORIES.TACTICS,
  TEMPLATE_CATEGORIES.ENDGAME
])

export const TEMPLATE_CATEGORY_LABELS = Object.freeze({
  [TEMPLATE_CATEGORIES.OPENING]: 'Opening',
  [TEMPLATE_CATEGORIES.CAPTURES]: 'Captures',
  [TEMPLATE_CATEGORIES.SAFETY]: 'Safety',
  [TEMPLATE_CATEGORIES.ACTIVITY]: 'Activity',
  [TEMPLATE_CATEGORIES.TACTICS]: 'Tactics',
  [TEMPLATE_CATEGORIES.ENDGAME]: 'Endgame'
})
