export const TEMPLATE_CATEGORIES = Object.freeze({
  OPENING: 'opening',
  CAPTURES: 'captures',
  DEFENSE: 'defense',
  SAFETY: 'defense',
  ACTIVITY: 'activity',
  TACTICS: 'tactics',
  KING_PRESSURE: 'king_pressure',
  PAWN_PLAY: 'pawn_play',
  ENDGAME: 'endgame'
})

export const TEMPLATE_CATEGORY_ORDER = Object.freeze([
  TEMPLATE_CATEGORIES.OPENING,
  TEMPLATE_CATEGORIES.CAPTURES,
  TEMPLATE_CATEGORIES.DEFENSE,
  TEMPLATE_CATEGORIES.PAWN_PLAY,
  TEMPLATE_CATEGORIES.ACTIVITY,
  TEMPLATE_CATEGORIES.TACTICS,
  TEMPLATE_CATEGORIES.KING_PRESSURE,
  TEMPLATE_CATEGORIES.ENDGAME
])

export const TEMPLATE_CATEGORY_LABELS = Object.freeze({
  [TEMPLATE_CATEGORIES.OPENING]: 'Opening',
  [TEMPLATE_CATEGORIES.CAPTURES]: 'Captures',
  [TEMPLATE_CATEGORIES.DEFENSE]: 'Defense',
  [TEMPLATE_CATEGORIES.ACTIVITY]: 'Activity',
  [TEMPLATE_CATEGORIES.TACTICS]: 'Tactics',
  [TEMPLATE_CATEGORIES.KING_PRESSURE]: 'King Pressure',
  [TEMPLATE_CATEGORIES.PAWN_PLAY]: 'Pawn Play',
  [TEMPLATE_CATEGORIES.ENDGAME]: 'Endgame'
})
